// questions.js
const data = [
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which programming language shares its name with an island in Indonesia?",
    correct_answer: "Java",
    options: ["Python", "C", "Jakarta", "Java"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "According to the International System of Units, how many bytes are in a kilobyte of RAM?",
    correct_answer: "1000",
    options: ["512", "1024", "500", "1000"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which computer hardware device provides an interface for all other connected devices to communicate?",
    correct_answer: "Motherboard",
    options: [
      "Central Processing Unit",
      "Hard Disk Drive",
      "Random Access Memory",
      "Motherboard",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "How many values can a single byte represent?",
    correct_answer: "256",
    options: ["8", "1", "1024", "256"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "What is the code name for the mobile operating system Android 7.0?",
    correct_answer: "Nougat",
    options: ["Ice Cream Sandwich", "Jelly Bean", "Marshmallow", "Nougat"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "How long is an IPv6 address?",
    correct_answer: "128 bits",
    options: ["32 bits", "64 bits", "128 bytes", "128 bits"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "What is the name of Layer 7 of the OSI model?",
    correct_answer: "Application",
    options: ["Session", "Network", "Presentation", "Application"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "If you were to code software in this language you'd only be able to type 0's and 1's.",
    correct_answer: "Binary",
    options: ["JavaScript", "C++", "Python", "Binary"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "In any programming language, what is the most common way to iterate through an array?",
    correct_answer: "'For' loops",
    options: ["'If' Statements", "'Do-while' loops", "'While' loops", "'For' loops"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "In the programming language Java, which of these keywords would you put on a variable to make sure it doesn't get modified?",
    correct_answer: "Final",
    options: ["Static", "Private", "Public", "Final"],
  },
];

export default data;
